name: Ubuntu20

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install
        run: ./.ci/ci_before_install.sh

      - name: Build
        run: ./.ci/ci_test_build.sh

      - name: Test
        continue-on-error: true
        run: ./.ci/ci_run_tests.sh